name: TestCafe CI

on:
  push:
    branches:
      - main
      
jobs:
  setup:
    name: Setup do Projeto
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Configura Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
  
  test:
    name: Testes End-to-End
    runs-on: windows-latest
    needs: setup

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v2      

      - name: Instala dependencias
        run: npm install

      - name: Atribui variaveis de ambiente
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "USER=${{ secrets.USER }}" >> .env
          echo "PASS=${{ secrets.PASS }}" >> .env
          echo "BASE_URL=${{ secrets.API_URL }}" >> .env
          echo "USER=${{ secrets.USER_API }}" >> .env
          echo "PASS=${{ secrets.PASS_API }}" >> .env
        
      - name: Executa os testes   
        run: npm run ci
